[package]
name = "brigadier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.9.1"
linked-hash-map = "0.5.6"
slab = "0.4.7"
slotmap = "1.0.6"
thiserror = "1.0.32"
